### PR TITLE
Replace serde_yaml with serde_json internally

### PR DESCRIPTION
**Pull request by rezvaneh**
We replaced `serde_yaml` with `serde_json` to simplify writing tests and conversion to protobuf 

**Which issue(s) this PR fixes**:
https://github.com/googleforgames/quilkin/issues/507

### CODE REVIEW

**Review by bombsimon — APPROVED** [review]
This surely looks way more convenient, LGTM!

**Review by XAMPPRocky — APPROVED** [review]
LGTM! Just need to run `cargo fmt` and fix the `cargo clippy` lints, and it should be good to go.

**Comment by rezvaneh** [comment]
> LGTM! Just need to run `cargo fmt` and fix the `cargo clippy` lints, and it should be good to go.

I had ran them before, can you see what error says?

**Comment by XAMPPRocky** [comment]
```
Step #4 - "test-quilkin": error: casting integer literal to `i64` is unnecessary
Step #4 - "test-quilkin":    --> src/filters/capture.rs:144:25
Step #4 - "test-quilkin":     |
Step #4 - "test-quilkin": 144 |                 "size": 3 as i64,
Step #4 - "test-quilkin":     |                         ^^^^^^^^ help: try: `3_i64`
Step #4 - "test-quilkin":     |
Step #4 - "test-quilkin":     = note: `-D clippy::unnecessary-cast` implied by `-D warnings`
Step #4 - "test-quilkin":     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
Step #4 - "test-quilkin": 
Step #4 - "test-quilkin": error: casting integer literal to `i64` is unnecessary
Step #4 - "test-quilkin":    --> src/filters/capture.rs:162:25
Step #4 - "test-quilkin":     |
Step #4 - "test-quilkin": 162 |                 "size": 3 as i64,
Step #4 - "test-quilkin":     |                         ^^^^^^^^ help: try: `3_i64`
Step #4 - "test-quilkin":     |
Step #4 - "test-quilkin":     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
Step #4 - "test-quilkin": 
Step #4 - "test-quilkin": error: useless conversion to the same type: `&str`
Step #4 - "test-quilkin":    --> src/xds/cluster.rs:785:38
Step #4 - "test-quilkin":     |
Step #4 - "test-quilkin": 785 |         let value = dyn_metadata.get("key-a".into()).unwrap();
Step #4 - "test-quilkin":     |                                      ^^^^^^^^^^^^^^ help: consider removing `.into()`: `"key-a"`
Step #4 - "test-quilkin":     |
Step #4 - "test-quilkin":     = note: `-D clippy::useless-conversion` implied by `-D warnings`
Step #4 - "test-quilkin":     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
Step #4 - "test-quilkin": 
Step #4 - "test-quilkin": error: could not compile `quilkin` due to 3 previous errors
Step #4 - "test-quilkin": make: *** [Makefile:55: test-quilkin] Error 101
Finished Step #4 - "test-quilkin"
```

**Pull request merged**
