### PR TITLE
Build single token -> address map

### PR DESCRIPTION
**Pull request by Jake-Shadle**
Resolves: #975

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Have you run any benchs on this to see if and/or how fast it is compared to the previous approach?

**Comment by Jake-Shadle** [comment]
## main
```
token_router                      fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ token_router                                 │               │               │               │         │
   ├─ HashedTokenRouter                         │               │               │               │         │
   │  ├─ multi:2..128:duplicates  1.572 µs      │ 36.19 µs      │ 13.61 µs      │ 14.29 µs      │ 100     │ 100
   │  │                           67.36 TB/s    │ 2.927 TB/s    │ 7.781 TB/s    │ 7.414 TB/s    │         │
   │  ├─ multi:2..128:unique      1.432 µs      │ 44.41 µs      │ 13.93 µs      │ 15.04 µs      │ 100     │ 100
   │  │                           73.91 TB/s    │ 2.384 TB/s    │ 7.601 TB/s    │ 7.04 TB/s     │         │
   │  ├─ single:duplicates        1.021 µs      │ 19.84 µs      │ 6.211 µs      │ 6.677 µs      │ 100     │ 100
   │  │                           1.608 TB/s    │ 82.79 GB/s    │ 264.5 GB/s    │ 246 GB/s      │         │
   │  ╰─ single:unique            720.7 ns      │ 25.44 µs      │ 5.725 µs      │ 6.49 µs       │ 100     │ 100
   │                              2.28 TB/s     │ 64.58 GB/s    │ 287 GB/s      │ 253.2 GB/s    │         │
   ╰─ TokenRouter                               │               │               │               │         │
```

## PR
```
token_router                      fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ token_router                                 │               │               │               │         │
   ├─ HashedTokenRouter                         │               │               │               │         │
   │  ├─ multi:2..128:duplicates  700.7 ns      │ 5.058 µs      │ 961.2 ns      │ 1.044 µs      │ 100     │ 100
   │  │                           151.2 TB/s    │ 20.94 TB/s    │ 110.2 TB/s    │ 101.4 TB/s    │         │
   │  ├─ multi:2..128:unique      690.7 ns      │ 4.237 µs      │ 931.7 ns      │ 1.008 µs      │ 100     │ 100
   │  │                           153.3 TB/s    │ 24.99 TB/s    │ 113.6 TB/s    │ 104.9 TB/s    │         │
   │  ├─ single:duplicates        490.7 ns      │ 3.606 µs      │ 780.7 ns      │ 822.4 ns      │ 100     │ 100
   │  │                           3.348 TB/s    │ 455.5 GB/s    │ 2.104 TB/s    │ 1.997 TB/s    │         │
   │  ╰─ single:unique            480.7 ns      │ 3.446 µs      │ 790.7 ns      │ 814.7 ns      │ 100     │ 100
   │                              3.418 TB/s    │ 476.8 GB/s    │ 2.078 TB/s    │ 2.017 TB/s    │         │
   ╰─ TokenRouter                               │               │               │               │         │
```

**Comment by XAMPPRocky** [comment]
Nice, 2x as fast 😄

**Review by XAMPPRocky — APPROVED** [review]

**Comment by markmandel** [comment]
Any reason to keep the default TokenRouter? Seems like `HashedTokenRouter` should just become the `TokenRouter`?

**Comment by Jake-Shadle** [comment]
Yes.

**Pull request merged**
