### PR TITLE
Add Pprof profiling endpoint

### PR DESCRIPTION
**Pull request by XAMPPRocky**
This adds a proof profiling endpoint for Quilkin, allowing Quilkin to be continuously profiled using tools like Grafana Phlare.

### CODE REVIEW

**Review by markmandel — APPROVED** [review]

**Comment by markmandel** [comment]
Looks like a formatting issue, but otherwise should be fine.

Also thinking because of this PR, we should get another release out this month.

**Comment by XAMPPRocky** [comment]
Yeah, though I need to make some changes as with the current implementation, we run out of memory pretty quickly right now, so I need to add some limits to stop that.

**Comment by markmandel** [comment]
Oops, that's no good 😄 

I did have couple more thoughts this morning:

1. Should we have some kind of admin option to turn this off?
2. We should also document this somewhere 😁

**Comment by markmandel** [comment]
Just watching an amazing talk about continuous profiling at GDC -- rather than baking in profiling, instead we could look at a eBPF profiler such as https://pyroscope.io/ to run low overhead continuous profiling on both GameServers and Quilkin itself.

I believe the only requirements are to have debug symbols (in some capacity) and frame pointers (I have not looked into details, just writing notes post talk).

**Comment by XAMPPRocky** [comment]
Closed in favour of #875

**Pull request closed without merging**
