### PR TITLE
Fix: mdbook-variables failing on doc building.

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking

/kind bug

> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

**What this PR does / Why we need it**:

This PR should fix both the development docs being updated, and also the daily rebuild of our build container images that are used in CI.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

Also reported: https://gitlab.com/tglman/mdbook-variables/-/issues/3

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Hmm, seems like it's no getting any response from the status checks 🤔

**Comment by markmandel** [comment]
> Hmm, seems like it's no getting any response from the status checks thinking

Ooh, good chance for me to see if I can see if the CI is running.

I am wondering if for single PR's like this, it will take longer to merge, because it will run CI again (although that's not the worst thing).

**Comment by markmandel** [comment]
We have a build running for the merge queue - I'm not 100% sure if the right statuses are required for the new format, but we'll see how it pans out.

**Comment by markmandel** [comment]
Okay - so this is interesting. I've set the CI status for the CI-merge-queue (which is the trigger for merge queues) to be required, but not the CI system which runs on PR submission.

I'm not entirely sure if that's going to generally work, but I think it will for this PR. I can see the CI-merge-queue status running for the merge queue right now.

**Pull request merged**
