### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation
> /kind feature
> /kind hotfix

/kind release

**What this PR does / Why we need it**:

Changes for 0.4.0 release.

**Which issue(s) this PR fixes**:

Work on #647

**Special notes for your reviewer**:

Included a couple of small fixes for release checklist while I was at it.

### CODE REVIEW

**Comment by markmandel** [comment]
Gentle bump in getting approval for this release please 👋🏻. Travelling at the moment, but I've got some time to wrap this up today.

**Comment by XAMPPRocky** [comment]
@markmandel It looks good to me, I just want to write some prose to the top of the changelog talking about and highlighting the new features.

**Comment by markmandel** [comment]
Since the CHANGELOG is generated on each release, want to put the prose in the github release?

Once this PR is approved, I'll start a draft release, and you can put notes in there. Sounds good?

**Review by XAMPPRocky — APPROVED** [review]

**Comment by markmandel** [comment]
Draft: https://github.com/googleforgames/quilkin/releases/edit/untagged-0259e2ecfef7005470ce

Wrote a sacrificial draft, feel free to edit as you see fit.

**Pull request merged**
