### PR TITLE
ClusterMap benchmarks

### PR DESCRIPTION
**Pull request by Jake-Shadle**
During investigation of #837 (which fortunately? ended with the original issue not being observed) I added several benchmarks.

While getting familiar with the code, I noticed an easy win of `Locality` using 3 unnecessary heap allocations, now it uses 0, and no longer heap allocates during parsing. This also simplifies how it is serialized to/from json which gives slight speedups on both ends since it's not serializing as many fields. Really, locality is essentially an opaque identifier as far as the codebase is concerned, and it could probably be even more simplified to a single hash value, but that can be done separately, this was mainly just to see numbers change in the benchmarks.

### CODE REVIEW

**Review by XAMPPRocky — APPROVED** [review]

**Comment by XAMPPRocky** [comment]
We just need to add an exception in the cargo-deny for xxhash's `BSL-1.0` (Boost Software Licence), that is allowed by Google and we already do the work of including licences in distribution because it's a requirement for Apache. https://opensource.google/documentation/reference/thirdparty/licenses#notice

**Comment by markmandel** [comment]
> We just need to add an exception in the cargo-deny for xxhash's `BSL-1.0` (Boost Software Licence), that is allowed by Google and we already do the work of including licences in distribution because it's a requirement for Apache. https://opensource.google/documentation/reference/thirdparty/licenses#notice

Just making a note for myself - if you add the exception, this will add this notice to our licence.html document - but I do need to do the work to include it in our release .zip (which is easy enough to do) -- I'll write a ticket for this now so I remember to do it before the next release. The licence.html file is already in the Docker image.

**Comment by Jake-Shadle** [comment]
Is all of that necessary? I can just take it out, I was only using it for testing purposes, and it's a dev only dependency so not part of any release artifacts.

**Comment by markmandel** [comment]
> Is all of that necessary? I can just take it out, I was only using it for testing purposes, and it's a dev only dependency so not part of any release artifacts.

We already do 95% of the work already to stay in compliance with OSS licencing - so it's not a big step to add this extra piece. We should probably ship the licence.html anyway in the zip to be honest - so it's work I'll do before our next release anyway whether you want to keep the dependency or not. Up to you 👍🏻

**Comment by XAMPPRocky** [comment]
Sorry, I was eager to bench with these improvements, so I pushed a commit to add the exception 😄

**Pull request merged**
