### PR TITLE
Remove built dependency

### PR DESCRIPTION
**Pull request by Jake-Shadle**
This was pulling in git2 and writing a lot of data that was never used
in the crate. This just changes build.rs to manually read the HEAD
commit information and set an env var.
AFAICT this is actually superior in every way to built since we no
longer have the extra dependencies, and we actually get up to date
information when the commit changes, which AFAICT was not the case with
built since it was not registering file changes.

### CODE REVIEW

**Review by XAMPPRocky — APPROVED** [review]

**Comment by XAMPPRocky** [comment]
These tests weren't flaky until today 😄

**Comment by markmandel** [comment]
> These tests weren't flaky until today 😄

Yeah! It's being really grumpy! I wonder what's up with that. 

If you see a flake, please chuck a comment in the PR of a c/p paste of the flake in the PR, and I'll do the same - that makes it easier to search for common flakes through GitHub search and eventually resolve (also we delete old build failures, so it's harder to see the history).

**Comment by XAMPPRocky** [comment]
> If you see a flake, please chuck a comment in the PR of a c/p paste of the flake in the PR, and I'll do the same - that makes it easier to search for common flakes through GitHub search and eventually resolve (also we delete old build failures, so it's harder to see the history).

It wasn't even the same test though which is odd, it was different tests.

**Comment by markmandel** [comment]
> It wasn't even the same test though which is odd, it was different tests.

Could be Cloud Build is having a grumpy day.

**Pull request merged**
