### PR TITLE
improvement: add note about measure units of jitter metric

### PR DESCRIPTION
**Pull request by zifter**
**What type of PR is this?**
/kind documentation

**What this PR does / Why we need it**:
This PR improves documentation

### CODE REVIEW

**Review by XAMPPRocky — APPROVED** [review]

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Review by markmandel — APPROVED** [review]

**Comment by XAMPPRocky** [comment]
@markmandel I think something went wrong with cloud build.

**Comment by XAMPPRocky** [comment]
@zifter Oh you, also need to sign the CLA for this be merged.

**Comment by zifter** [comment]
@XAMPPRocky i've done it more a long time ago
there is an issue with bot, not with my CLA 
https://github.com/googleforgames/quilkin/commit/4ef2ec28bb73b2d2f50b6b1cf5c7da3eac223728 Author: @quilkin-bot <84364394+quilkin-bot​@users.noreply.github.com>

**Comment by markmandel** [comment]
Weird, the quilkin bot is failing CLA. It shouldn't be a thing that it even worries about. I'll override it if need be.

**Comment by markmandel** [comment]
/gcbrun

(this is needed for people who don't have read access to the repo so the Cloud Build script runs - I forgot this as well)

**Comment by markmandel** [comment]
Ah, found the issue with the bot, that should be fixed now. Weird flake in the unit tests:

```
---- ipv6_firewall_allow stdout ----
thread 'ipv6_firewall_allow' panicked at src/components/proxy.rs:94:91:
called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1073:23
```

Will retry.

**Comment by zifter** [comment]
any updates? :)

**Comment by markmandel** [comment]
whoops! Thanks for the ping.

**Pull request merged**
