### PR TITLE
Unit and integration test debugging enhancements

### LINKED ISSUE #695: Print pod logs when steps fail in kubernetes integration tests
Currently when the agones tests fail all you usually see is the `Elapsed` error. It would be nice if we added an error handler task to the agones integration, that whenever a task for a pod fails it outputs the logs from that pod, as well as the pod description, so that you can get a detailed overview of what went wrong in the test rather than just a "exceeded timeout".

### PR DESCRIPTION
**Pull request by markmandel**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, press enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind breaking
> /kind bug
> /kind cleanup
> /kind documentation

/kind feature

> /kind hotfix

**What this PR does / Why we need it**:

* Finer control over log levels and filters by allowing env filters in a new `enable_log(filter: impl Into<EnvFilter>)` implementation.
* On the `agones` integration side a new `debug_pods(client: &Client, labels: String)` function that will output both the Events and all the logs for any pods that match a given selector.
* Example of use within a currently failing `agones_token_router` agones integration test in PR #712.

**Which issue(s) this PR fixes**:

Closes #695

**Special notes for your reviewer**:

The full log of a pod can end up being quite large. We'll see how it ends up looking in cloud build.

### CODE REVIEW

**Comment by markmandel** [comment]
@XAMPPRocky in case not obvious, this is a PR against your PR, so I could add necessary debugging to work out what's going wrong.

It gave me a bit of an idea now 😄 but I'm curious to see if it's obvious within the cloud build output.

**Review by XAMPPRocky — APPROVED** [review]

**Comment by markmandel** [comment]
Hmnn, I was hoping the log output would wrap. Lemme see if I can break it up line by line.

**Comment by markmandel** [comment]
Now outputting with each log line as a line. Lemme know which one you like more.

**Comment by markmandel** [comment]
I think that's way better broken out by line.

🤔 Would it be better if I broke out these utilities into it's own PR off main, and then came back around to https://github.com/googleforgames/quilkin/issues/695 ? (I'm leaning that way).

Looks like the PR is having some impact on the /ready http endpoint (I've not dug in yet).

**Comment by XAMPPRocky** [comment]
Yeah splitting it up makes sense though similarly, I'm still having trouble seeing what the cause is.

**Comment by markmandel** [comment]
Not sure - I think I'll have to build it and see what the readiness probe returns.

I'll split out the PR now though. Closing this one.

**Pull request closed without merging**
