### PR TITLE
Remove config being picked up in the CLI

### PR DESCRIPTION
**Pull request by XAMPPRocky**
Part of #700 this PR removes `Config` from being picked up in the CLI for now. So now the only way to provide configuration is through the file provider for a service.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
@markmandel This seems to be failing in a weird way that I can't tell what's happening.

```
Finished Step #6 - "test-quilkin-image-default-config-file"
ERROR
ERROR: build step 6 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 255
Step #9 - "test-agones": make: *** [Makefile:209: push] Terminated
Step #4 - "test-docs": [0m
```

**Comment by markmandel** [comment]
Did you delete your comment?

Looks like the change broke the test that attempts to run the default Docker proxy image:

```
Already have image (with digest): gcr.io/cloud-builders/docker
{"timestamp":"2023-07-18T12:21:12.198881Z","level":"INFO","fields":{"message":"Starting Quilkin","version":"0.7.0-dev","commit":"cae0736c50862e687407775846eda1d351155ca4"},"target":"quilkin::cli","filename":"src/cli.rs"}
{"timestamp":"2023-07-18T12:21:12.199228Z","level":"INFO","fields":{"message":"Starting admin endpoint","address":"[::]:8000"},"target":"quilkin::admin","filename":"src/admin.rs"}
{"timestamp":"2023-07-18T12:21:12.199669Z","level":"ERROR","fields":{"message":"fatal error","error":"`quilkin proxy` requires at least one `to` address or `management_server` endpoint.","error_debug":"`quilkin proxy` requires at least one `to` address or `management_server` endpoint."},"target":"quilkin","filename":"src/main.rs"}
```

https://github.com/googleforgames/quilkin/blob/ea5509f74c7c9b2048542ee2d8c6b1fc29112b4a/cloudbuild.yaml#L55-L63

Do we want to remove the Config search completely for this development path?

If we want to maintain a search path, and since we'll have multiple files we could do `/etc/quilkin/quilkin.yaml`  (maybe for a backward compatibility / not break tests), and then load all  yaml files in `/etc/quilkin/quilkin.d/` for all the different `Kind` of configurations.

That would align with Linux config and we could likely keep a backward compatibility, merge features towards #700, still do releases and continue with this work until complete.

WDYT?

**Comment by XAMPPRocky** [comment]
Yeah I figured out what's wrong with this, I need to also add the file provider to the proxy service so that the examples work.

> Do we want to remove the Config search completely for this development path?

No no, I want move proxy to being provider based like the other services. So you'd write `quilkin proxy file` instead, because that would also allow for `quilkin proxy agones` where you have the discovery happening in a single service.

**Comment by markmandel** [comment]
> No no, I want move proxy to being provider based like the other services. So you'd write `quilkin proxy file` instead, because that would also allow for `quilkin proxy agones` where you have the discovery happening in a single service.

Got it 👍🏻 

Yeah, that makes 100% sense then to remove it.

Or if you want to do this + `quilkin proxy file`, all in one PR, that could mean we could keep the cloudbuild test step?

Just thinking through removing and adding test steps is all.

**Comment by XAMPPRocky** [comment]
Yeah exactly, I'll update this with adding that.

**Comment by XAMPPRocky** [comment]
Needs more to be mergeable

**Pull request closed without merging**
