### PR TITLE
Make MAX_DELAY of tryhard configurable

### PR DESCRIPTION
**Pull request by zezhehh**
**What type of PR is this?**
/kind feature

**What this PR does / Why we need it**:

The default `MAX_DELAY` for `Provider::task` (5min), is way too long for our project, so we'd like it configurable. 

**Special notes for your reviewer**:

Not sure if it's a good solution, but I'll appreciate any input.

### CODE REVIEW

**Comment by andersroos** [comment]
Would be a work around for this issue: https://github.com/googleforgames/quilkin/issues/734

If we can put the max delay at 1-2 seconds or so the issue wouldn't be noticable.

**Comment by markmandel** [comment]
🤔 if it's a workaround for what breaks the experience - should we instead just hardcode the max retry delay value to something like 5 seconds? (or even 2 seconds - it's not a lot of QPS), rather than have to create a new CLI API that potentially needs to be maintained going forward?

This also seems like a bug that should be reported/fixed in https://github.com/EmbarkStudios/tryhard, yeah?

**Comment by zezhehh** [comment]
> 🤔 if it's a workaround for what breaks the experience - should we instead just hardcode the max retry delay value to something like 5 seconds? (or even 2 seconds - it's not a lot of QPS), rather than have to create a new CLI API that potentially needs to be maintained going forward?
> 
> This also seems like a bug that should be reported/fixed in [EmbarkStudios/tryhard](https://github.com/EmbarkStudios/tryhard), yeah?

Either works for us. I'm just not sure if a shorter max_delay will break other people's current systems. We haven't had a chance to explore `tryhard` yet, might do it later. :D

**Comment by markmandel** [comment]
@XAMPPRocky WDYT? I'm tempted to just drop this down to 2 seconds as a workaround, and then go hunt upstream to `try_hard` to confirm if it resets backoff on success.

**Comment by XAMPPRocky** [comment]
@markmandel I agree

**Pull request closed without merging**
