### PR TITLE
GH Action: Sizing labels on PRs

### PR DESCRIPTION
**Pull request by markmandel**
I miss this from other projects I work on. I find it makes things easier as a reviewer, as you can quickly identify smaller PRs that require less review and get them reviewed fast, and make sure you block out time for the larger submissions.

I do like the touch with this one that it will ping you a reminder that you might want to split up your PR if you are over 1000 lines 🙂

### CODE REVIEW

**Comment by markmandel** [comment]
Hmnnn. I gave the labeler the same token as the Cloud notifier bot, and gave quilkin-bot triage access to the repo, so I'm a little confused 🤔

**Comment by markmandel** [comment]
So this is hard to test, but it shouldn't break anything `pull_request_target` - runs the code from `main` on pull request, which will be able to apply the label once this has been merged 🤞🏻  - but won't for this, as the action gets passed a read/write token at that point.

See: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

**Comment by XAMPPRocky** [comment]
> See: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Didn't see, this, glad to know you can have workflows trigger other workflows now.

**Review by XAMPPRocky — APPROVED** [review]

**Comment by markmandel** [comment]
Let's see if this works :)

**Pull request merged**
