### PR TITLE
Implement xDS in Quilkin

### PR DESCRIPTION
**Pull request by XAMPPRocky**
This is couple of changes, and unfortunately it's a lot of interconnected pieces so, it isn't easy to split up into seperate PRs, so I'll instead list the changes below. This represents all the required changes needed to run Quilkin as a load balancer.

- Added `manage` command with two subcommand providers, `agones`, and `file`.
- Added a xDS management server for Agones, and one that watches a config file.
- Refactor xDS client to better match the new servers.
- `SharedFilterChain` is now serializable and implements `Filter`.
- `Config` represents the current state of Quilkin, not just the configuration file. This dramatically simplifies code that updates the running state of Quilkin. Making easy to apply updates from xDS discovery responses.
- `Config` now implements `JsonSchema`.
- Updated error type in `Filter` conversion code.
- Moved admin from proxy into its own `admin` module, as it is now used for both the edge proxy and the management server.
- Added compatibility with `ClusterLocalities` and `ClusterLoadAssignment`.
- Changed match config to reuse `crate::config::Filter`, and be compatible with `envoy.config.listener.v3.Filter`.
- Fixed capture documentation.
- Added more `tracing` traces.

### CODE REVIEW

**Comment by markmandel** [comment]
Just checking in, seeing if you would like some review or not, of if you are happy working on the PR and pulling out chunks as needed (also noting that the quilkin-bot isn't deleting the old comments? weird)

**Comment by markmandel** [comment]
Pretty sure you are on break at the moment, but just wanted to check in to see if you were still going to create a new PR for this work?

**Comment by XAMPPRocky** [comment]
@markmandel I was going to but I need to rebase on top of your changes to some of the tests first and I couldn't quite get it to work yet.

**Comment by markmandel** [comment]
Got it! No worries! Just wanted to check 👍🏻

**Comment by markmandel** [comment]
One thought I had: You could split out the deletion of all the Go xDS functionality into it's own PR. 

Gets some of the work in there, and takes a good chunk out of the rest of the PR.

Just a thought though.

**Comment by XAMPPRocky** [comment]
Yeah, I can once I’m back, since I have to rebase anyway, if you want to delete earlier feel free, it’s no extra effort for me.

**Comment by markmandel** [comment]
No worries - I figured as much.

I might take on the deletion 👍🏻 get the ball rolling.

**Pull request closed without merging**
