### PR TITLE
hash mode load balancer

### PR DESCRIPTION
**Pull request by gilesheron**
hopefully this time all commits are squashed, and I've managed to get the correct email address.

have also added one extra test - that if we vary the port but keep the same IP that >1 path is picked.

### CODE REVIEW

**Comment by markmandel** [comment]
On CLA, still seeing @users.noreply.github.com email address. I see the same when I look at the git log for your PR

```
commit 51f8aafac4bfe3fd023f63bef396e3a582913a7c (HEAD -> hashed_load_balance)
Author: Giles Heron <gilesheron@users.noreply.github.com>
Date:   Fri Aug 27 10:18:29 2021 +0100
```

https://www.git-tower.com/learn/git/faq/change-author-name-email/ is a great article on how to change globally, per repo and per commit (forward and in the past). This can then be `git push --force` up to the remote branch for this PR, and the CLA bot will kick in and find the new email 👍🏻 

Hit me up on Discord if you would like some realtime help.

**Comment by markmandel** [comment]
Checked CI, looks like [clippy](https://github.com/rust-lang/rust-clippy) is complaining a little:

```
error: redundant clone
   --> src/filters/load_balancer.rs:225:17
    |
225 |                 .clone()
    |                 ^^^^^^^^ help: remove this
    |
    = note: `-D clippy::redundant-clone` implied by `-D warnings`
note: this value is dropped without further use
   --> src/filters/load_balancer.rs:224:13
    |
224 | /             result_sequences
225 | |                 .clone()
    | |________________^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone

error: redundant clone
   --> src/filters/load_balancer.rs:251:17
    |
251 |                 .clone()
    |                 ^^^^^^^^ help: remove this
    |
note: this value is dropped without further use
   --> src/filters/load_balancer.rs:250:13
    |
250 | /             result_sequences
251 | |                 .clone()
    | |________________^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone

error: aborting due to 2 previous errors

error: could not compile `quilkin`
```

**Comment by markmandel** [comment]
So close! One commit (51f8aafac4bfe3fd023f63bef396e3a582913a7c) still has your github email on it.

**Comment by markmandel** [comment]
Hmnn, that's odd - the CLA should pass. I'll look into it.

**Comment by gilesheron** [comment]
closing as merged all changes into #381

**Pull request closed without merging**
