### PR TITLE
Make `Filter` an `async trait`.

### LINKED ISSUE #12: Filter idea: Asynchronous Filtering
Be able to have a filter that is processed Asynchronously.

This wouldn't have the ability to block, or route requests, but would allow for processing and parsing of packets not on the critical path.

We could also provide options to have a "sample-rate" in which you could retrieve a percentage of packets, either randomly, or deliberately sequentially, for systems that don't need to query every packet to process.

The main use case I can think of is doing something like deep introspection of packets for malicious elements - taking a random sample of packets for processing, could be fast enough to find a bad actor without them being able to cause large scale harm, without slowing down processing speed drastically.

### PR DESCRIPTION
**Pull request by XAMPPRocky**
This PR makes the `Filter` trait asynchronous, allowing implementors to insert yield points. It's worth noting that you could always spawn background tasks even before this change it just wouldn't have been useful. This PR doesn't change any behaviour other adding async, but this will also allow us to try things like cancellable, concurrent, and parallel filters.

This is currently built off #293 to reduce merge conflicts, the important work is in  https://github.com/googleforgames/quilkin/commit/7c0d5fd42afae63018debed77f58f1acec4cd204

closes #12

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
I ran a comparison benchmark, and there is no noticeable impact between this and the `main` branch. So with that in mind, I would prefer that we make these `async`. Also with the [push for GAT stabilisation](https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html) `async trait` is getting closer to stabilisation, so I'd rather have the capability of running filters as tasks and accept the `Box` for now.

comparison

**Comment by iffyio** [comment]
So I ran a quick load test with that C tool I linked earlier, I added a noop filter (simple filter that checks if the packet length is even and drops the packet if its odd, only to simulate _some_ logic though I only sent even length packets) then ran quilkin with a config that has 10 (not sure if this is too large or too small for a typical use case) noops in the filter chain.
On my machine without async the proxy could process in the range 300-380k pps, with async it could do 260-350k pps. Its not a drastic difference but it is significant (and its larger with more filters). I mentioned earlier that the criterion benchmark we have currently is proabably too noisy to be reliable, that could be why its not detecting any difference between the two branches.

My point is not only whether or not there's a perf difference but also that its weird to add such a change at the same time that we're trying to optimize the hot path by reducing clones/allocations etc I think if there comes a need to add async filters then we should accept the `async-trait` Boxing (hopefully by then there's rust support for async traits :crossed_fingers: or we're in a better shape per-wise) but there isn't any such a need that we know of today? so I don't see any upside

**Comment by markmandel** [comment]
> My point is not only whether or not there's a perf difference but also that its weird to add such a change at the same time that we're trying to optimize the hot path by reducing clones/allocations etc I think if there comes a need to add async filters then we should accept the async-trait Boxing (hopefully by then there's rust support for async traits crossed_fingers or we're in a better shape per-wise) but there isn't any such a need that we know of today? so I don't see any upside

I agree with this sentiment - unless we have a feature/use case that requires this change, it makes sense to leave these kinds of changes up until we need it. No need to add extra complexity if it's not required.

**Comment by XAMPPRocky** [comment]
> I agree with this sentiment - unless we have a feature/use case that requires this change, it makes sense to leave these kinds of changes up until we need it. No need to add extra complexity if it's not required.

In #309 you say *"There are lots of use cases for being able to send packets from a Filter,"*, that requires I/O, and if we're going to have filters performing I/O they need to use async so that we more control on how to react to filesystem failures, slow network requests, etc, and we also have #13 which is another filter which could take an indeterminate length. So I think we've already found plenty of reasons to have this feature, and have found very little cost to it.

**Comment by XAMPPRocky** [comment]
>  calling e.g into an ffi isn't inherently async, the same rules for our rust filters goes for the scriptable filter I imagine.

It isn't inherently asynchronous but's a lot harder to write code that handles indeterminism when it is a function rather than a task, like I don't know how you'd write a cancellable script filter without either using async or spawning a new thread. If we chose wasmtime we could have a fuel limit in the interpreter but that would require us to always have a fuel limit on any script which I don't think would be intuitive as a default.

**Comment by markmandel** [comment]
With #309, I don't feel like we have reached consensus there - it seems to me like there are a lot of questions unanswered. I'm not even sure that allowing a Filter to send a packet is a good idea at all -- maybe an entirely different construct is required?. With #13 - is this even a good idea? (Maybe it isn't) - what scripts would we want to support, if we did support them, what performance would we want - I have a lot of questions on both.

I'd love to see either one or the other ticket have a few "yep, that looks good to me, let's implement that" type comments before we start heading down towards implementation.

**Comment by gilesheron** [comment]
only just spotted this PR.   it certainly would have made writing my API lookup flavour of load-balancer easier (currently I'm spinning up a new OS thread for the API client and then using this trick: https://stackoverflow.com/a/66280983 to run an async fn from within the load-balancer that communicates with the API thread).

Feels to me like there are a bunch of things that could be pulled together here (e.g. #374 and #375).  From looking at the code we already have a session construct for returned traffic.  If we extended the session construct to outbound traffic then we could have a concept of a "routing" chain in addition to the filter chain, and have that chain run async and do things like load-balancing, stats export etc. that only need to happen once per session (or periodically for long-lived sessions...).

is it worth discussing this in the next community call?

**Comment by markmandel** [comment]
Would love to hear if more people have use cases for adding the async trait to the Filter, just because of the performance hit.

So if you find one, please share!

**Pull request closed without merging**
