### PR TITLE
Completely remove `slog` and replace with `tracing`

### LINKED ISSUE #317: Move from `slog` to `tracing`
[`tracing`](https://github.com/tokio-rs/tracing) is a diagnostic built and maintained by the Tokio team. It handles logging, but it provides a lot more as it's design for general instrumentation, for example there's a companion crate that uses the output to provide flamegraphs from the events. So using `tracing` would provide us with a lot more insight into what's happening at runtime than our current logging solution.

### PR DESCRIPTION
**Pull request by XAMPPRocky**
With the release of https://github.com/tokio-rs/console I wanted to move over to tracing sooner rather than later, so this pulls out all instances of `slog` and replaces them with `tracing`.

resolves #317

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
@markmandel Failure seems unrelated to the PR, not sure how to fix it.

**Review by iffyio — APPROVED** [review]

**Comment by markmandel** [comment]
> @markmandel Failure seems unrelated to the PR, not sure how to fix it.

That's a weird one. When in doubt, retry.

**Review by markmandel — APPROVED** [review]

**Comment by markmandel** [comment]
Looks like I can't re-run a build older than three days.

Easy way to rerun a build if you don't want to go to the console is: `git commit --amend --date=now` and then push that over the top. It'll fire a whole new build.

**Comment by XAMPPRocky** [comment]
@markmandel FWIW, I wrote that comment after retrying twice. I'll push an empty commit in the next couple days (on holidays)

**Comment by markmandel** [comment]
> @markmandel FWIW, I wrote that comment after retrying twice. I'll push an empty commit in the next couple days (on holidays)

AAAH. I can't tell anymore, because no history 😄 Sounds like I'll need try this locally and see if I can find where things are broken in the build system 👍🏻 No worries, I'll get on it tomorrow most likely.

**Comment by markmandel** [comment]
I worked it out! Since we no longer have slog-json, we don't have any MPL source code to grab, so the zip doesn't get created!

I'll come up with a fix in my draft branch, and you can include it in the PR 👍🏻

**Comment by markmandel** [comment]
Got it!

You will need to update `image/archive_dependencies.sh` like so (https://github.com/markmandel/quilkin/commit/b6c755007dc890a2f93d70cb80524caa011b4694), since slog-json is no longer a dependency.

I figure it would make more sense to be included in your PR, since the removal of `slog` is tied to this PR, rather than as a separate PR.

**Pull request merged**
